#pragma once

// FIXME: split up meta header `HICANNContainer.h"
#include "hal/HICANNContainer.h"

#include "hal/HICANN/Crossbar.h"
#include "hal/HICANN/DNCMerger.h"
#include "hal/HICANN/DNCMergerLine.h"
#include "hal/HICANN/DriverDecoder.h"
#include "hal/HICANN/FGBlock.h"
#include "hal/HICANN/FGConfig.h"
#include "hal/HICANN/FGControl.h"
#include "hal/HICANN/FGInstruction.h"
#include "hal/HICANN/FGStimulus.h"
#include "hal/HICANN/GbitLink.h"
#include "hal/HICANN/L1Address.h"
#include "hal/HICANN/Merger.h"
#include "hal/HICANN/MergerTree.h"
#include "hal/HICANN/RowConfig.h"
#include "hal/HICANN/STDPAnalog.h"
#include "hal/HICANN/STDPControl.h"
#include "hal/HICANN/STDPEval.h"
#include "hal/HICANN/STDPLUT.h"
#include "hal/HICANN/STDPTiming.h"
#include "hal/HICANN/SynapseDecoder.h"
#include "hal/HICANN/SynapseDriver.h"
#include "hal/HICANN/SynapseSwitch.h"
#include "hal/HICANN/FGErrorResult.h"
