#!/usr/bin/env python

from waflib.extras.gtest import summary

def depends(ctx):
    ctx('pywrap')
    ctx('pyublas')
    ctx('halbe')


def options(ctx):
    pass


def configure(cfg):
    if cfg.options.with_pywrap_bindings == False:
        cfg.fatal("Don't recurse into pyhalbe when bindings are disabled")


def build(bld):

    USES = [ 'halbe', 'BOOST4PYHALBE', 'PYHALBE', 'pyublas', 'pywrap', 'pywrapstdvector' ]

    bld(
            target         = 'pyhalbe',
            name           = 'pyhalbe_bindings',
            features       = 'cxx cxxshlib pypp pyembed pyext',
            script         = 'generate.py',
            gen_defines    = 'PYPLUSPLUS __STRICT_ANSI__ BOOST_PP_VARIADICS',
            defines        = 'PYBINDINGS',
            headers        = 'pyhalbe.h',
            use            = USES + ['pycellparameters', 'pyhalco_hicann_v2', 'pyhalco_common_files'],
            install_path   = '${PREFIX}/lib',
            includes       = '.',
    )

    bld(
            target         = 'Coordinate',
            features       = 'use',
            use            = USES + ['pycellparameters', 'pyhalco_hicann_v2'],
    )

    bld(
        name='pyhalbe',
        features='py use',
        source = bld.path.ant_glob('pyhalbe_*.py'),
        relative_trick=True,
        use='pyhalbe_bindings',
        install_path='${PREFIX}/lib'
    )

    bld(
        name            = "pyhalbe_test_dep",
        source          = ['test/HWTest.py', 'test/Test.py'],
        features        = 'py',
        install_path    = '${PREFIX}/lib',
    )

    bld(
        name            = "pyhalbe_tests",
        tests           = bld.path.ant_glob('**/halbe_test_*.py'),
        features        = 'use pytest',
        use             = 'pyhalbe',
        install_path    = '${PREFIX}/bin',
        test_environ    = { 'PYHALBE_API_CHECK' : '1' },
    )

    bld(
        name            = "pyhalbe_hwtests",
        tests           = bld.path.ant_glob('**/halbe_hwtest_*.py'),
        features        = 'use pytest',
        use             = 'pyhalbe',
        install_path    = '${PREFIX}/bin',
        test_environ    = { 'PYHALBE_API_CHECK' : '1' },
        skip_run        = True,
    )
    bld.add_post_fun(summary)
