#!/usr/bin/env python

import os
from waflib import Utils

bld(
    target       = 'halbe_SWRealtimeLatencyMeasurementTool',
    features     = 'cxx cxxprogram pyembed',
    source       = bld.path.ant_glob('SWRealtimeLatencyMeasurementTool.cpp'),
    use          = [ 'halbe', 'BOOST4TOOLS' ],
    install_path = '${PREFIX}/bin',
)

bld(
    target       = 'halbe_HWRealtimeLatencyMeasurementTool',
    features     = 'cxx cxxprogram pyembed',
    source       = bld.path.ant_glob('HWRealtimeLatencyMeasurementTool.cpp'),
    use          = [ 'halbe', 'BOOST4TOOLS' ],
    install_path = '${PREFIX}/bin',
)

bld.install_files(
        '${PREFIX}/bin',
        'halbe_run_hardware_tests.sh',
        chmod=Utils.O755,
        relative_trick=False
)

bld.install_files(
        '${PREFIX}/bin',
        bld.path.ant_glob('*.py'),
        chmod=Utils.O755,
        relative_trick=False
)

bld(
    target       = 'halbe_anarm_server',
    features     = 'cxx cxxprogram',
    source       = bld.path.ant_glob('anarm_server.cpp'),
    use          = [ 'halbe', 'rcf', 'BOOST4TOOLS' ],
    install_path = '${PREFIX}/bin',
)

bld(
    target       = 'halbe_create_fake_container',
    features     = 'cxx cxxprogram',
    source       = bld.path.ant_glob('halbe_create_fake_container.cpp'),
    use          = [ 'halbe', 'BOOST4TOOLS' ],
    install_path = '${PREFIX}/bin',
)
